globalThis.EXPENSIUM_UI = Object.freeze({
  "en": {"search":"Search languages","auto":"Automatic","enabled":"Enabled","disabled":"Disabled","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "cs": {"search":"Hledat jazyky","auto":"Automaticky","enabled":"Zapnuto","disabled":"Vypnuto","modeAuto":"Auto","modeStandard":"Běžný","modePremium":"Premium"},
  "sk": {"search":"Hľadať jazyky","auto":"Automaticky","enabled":"Zapnuté","disabled":"Vypnuté","modeAuto":"Auto","modeStandard":"Bežný","modePremium":"Premium"},
  "de": {"search":"Sprachen suchen","auto":"Automatisch","enabled":"Aktiviert","disabled":"Deaktiviert","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "pl": {"search":"Szukaj języków","auto":"Automatycznie","enabled":"Włączone","disabled":"Wyłączone","modeAuto":"Auto","modeStandard":"Zwykły","modePremium":"Premium"},
  "nl": {"search":"Talen zoeken","auto":"Automatisch","enabled":"Ingeschakeld","disabled":"Uitgeschakeld","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "fr": {"search":"Rechercher des langues","auto":"Automatique","enabled":"Activé","disabled":"Désactivé","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "es": {"search":"Buscar idiomas","auto":"Automático","enabled":"Activado","disabled":"Desactivado","modeAuto":"Auto","modeStandard":"Normal","modePremium":"Premium"},
  "it": {"search":"Cerca lingue","auto":"Automatico","enabled":"Attivato","disabled":"Disattivato","modeAuto":"Auto","modeStandard":"Normale","modePremium":"Premium"},
  "pt": {"search":"Pesquisar idiomas","auto":"Automático","enabled":"Ativado","disabled":"Desativado","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "ru": {"search":"Поиск языков","auto":"Автоматически","enabled":"Включено","disabled":"Выключено","modeAuto":"Авто","modeStandard":"Обычный","modePremium":"Premium"},
  "uk": {"search":"Пошук мов","auto":"Автоматично","enabled":"Увімкнено","disabled":"Вимкнено","modeAuto":"Авто","modeStandard":"Звичайний","modePremium":"Premium"},
  "tr": {"search":"Dil ara","auto":"Otomatik","enabled":"Açık","disabled":"Kapalı","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "ar": {"search":"البحث عن اللغات","auto":"تلقائي","enabled":"مفعّل","disabled":"معطّل","modeAuto":"تلقائي","modeStandard":"عادي","modePremium":"Premium"},
  "he": {"search":"חיפוש שפות","auto":"אוטומטי","enabled":"מופעל","disabled":"מושבת","modeAuto":"אוטומטי","modeStandard":"רגיל","modePremium":"Premium"},
  "hi": {"search":"भाषाएँ खोजें","auto":"स्वचालित","enabled":"चालू","disabled":"बंद","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "id": {"search":"Cari bahasa","auto":"Otomatis","enabled":"Aktif","disabled":"Nonaktif","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "vi": {"search":"Tìm ngôn ngữ","auto":"Tự động","enabled":"Bật","disabled":"Tắt","modeAuto":"Auto","modeStandard":"Standard","modePremium":"Premium"},
  "ja": {"search":"言語を検索","auto":"自動","enabled":"オン","disabled":"オフ","modeAuto":"自動","modeStandard":"通常","modePremium":"Premium"},
  "ko": {"search":"언어 검색","auto":"자동","enabled":"켜짐","disabled":"꺼짐","modeAuto":"자동","modeStandard":"일반","modePremium":"Premium"},
  "zh-Hans": {"search":"搜索语言","auto":"自动","enabled":"已启用","disabled":"已禁用","modeAuto":"自动","modeStandard":"普通","modePremium":"Premium"},
  "zh-Hant": {"search":"搜尋語言","auto":"自動","enabled":"已啟用","disabled":"已停用","modeAuto":"自動","modeStandard":"一般","modePremium":"Premium"}
});
